# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS

pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'

pod 'Toast', '~> 3.0'
pod 'Bugly'

end
